services:
  neohearts-api:
    build:
      context: ./server
      dockerfile: ./server/Dockerfile
    ports:
      - "5177:5177"
    # restart: always
    env_file:
      - ./server/.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
      # Add any other environment variables your API needs below
      # - ConnectionStrings__DefaultConnection=your_connection_string

    networks:
      - neohearts-network

  nginx:
    image: nginx:1.28-alpine
    container_name: webserver
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    networks:
      - neohearts-network
    depends_on:
      - neohearts-api
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
        # entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - neohearts-network

networks:
  neohearts-network:
    driver: bridge
