name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.GCP_SSH_KEY }}

      - name: Deploy to GCP VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.GCP_SSH_USER }}@${{ secrets.GCP_SSH_HOST }} << 'EOF'
            set -e
            cd /neohearts-api
            echo "Pulling latest code..."
            git fetch origin main
            git reset --hard origin/main
            echo "Rebuilding and restarting containers..."
            docker compose down
            docker compose build
            docker compose up -d
            echo "Deployment complete."
          EOF
